// 15×15 Maxi crossword puzzles, NYT-style format.
// These were generated algorithmically from a public-domain grid pattern + macOS wordlist
// + WordNet definitions. Quality varies — some clues are placeholder ("N-letter word").
// Use the editor's "Import .puz" button to add hand-curated puzzles.

const PUZZLES = [
  {
    solution: [
      ['S','T','U','F','F',null,'A','C','R','E',null,'A','D','A','M'],
      ['H','O','N','O','R',null,'N','O','E','L',null,'D','A','M','O'],
      ['A','T','T','R','A','C','T','I','V','E',null,'D','R','O','P'],
      ['K','A','I',null,'N','A','I','L',null,'C','H','E','E','S','E'],
      ['E','L','L','I','C','E',null,null,null,'T','E','N','D',null,null],
      [null,null,null,'T','O','S','S','E','R',null,'A','D','E','L','A'],
      ['T','H','I','S',null,'A','N','N','E',null,'R','A','V','E','L'],
      ['H','E','R',null,'P','R','O','J','E','C','T',null,'I','S','T'],
      ['A','R','O','M','A',null,'R','O','S','E',null,'A','L','S','O'],
      ['T','E','N','O','R',null,'E','Y','E','L','I','D',null,null,null],
      [null,null,'S','O','L','D',null,null,null,'T','R','A','V','E','L'],
      ['E','N','T','R','E','E',null,'S','H','I','V',null,'I','L','Y'],
      ['R','O','O','M',null,'P','E','N','I','C','I','L','L','I','N'],
      ['M','O','N','A',null,'T','O','O','L',null,'N','Y','L','O','N'],
      ['A','N','E','N',null,'H','O','W','L',null,'G','R','A','T','E'],
    ],
    clues: {
      across: [

        { number:1, row:0, col:0, len:5, clue:'The tangible substance that goes into the makeup of a physical object' },
        { number:6, row:0, col:6, len:4, clue:'A unit of area  used in English-speaking countries' },
        { number:10, row:0, col:11, len:4, clue:'In Judeo-Christian mythology' },
        { number:14, row:1, col:0, len:5, clue:'A tangible symbol signifying approval or distinction' },
        { number:15, row:1, col:6, len:4, clue:'Period extending from Dec. 24 to Jan. 6' },
        { number:16, row:1, col:11, len:4, clue:'4-letter word' },
        { number:17, row:2, col:0, len:10, clue:'Pleasing to the eye or mind especially through beauty or charm' },
        { number:19, row:2, col:11, len:4, clue:'A shape that is spherical and small' },
        { number:20, row:3, col:0, len:3, clue:'3-letter word' },
        { number:21, row:3, col:4, len:4, clue:'Horny plate covering and protecting part of the dorsal surface of t...' },
        { number:22, row:3, col:9, len:6, clue:'A solid food prepared from the pressed curd of milk' },
        { number:24, row:4, col:0, len:6, clue:'6-letter word' },
        { number:26, row:4, col:9, len:4, clue:'Have care of or look after' },
        { number:27, row:5, col:3, len:6, clue:'British slang for a contemptible person' },
        { number:31, row:5, col:10, len:5, clue:'5-letter word' },
        { number:34, row:6, col:0, len:4, clue:'4-letter word' },
        { number:37, row:6, col:5, len:4, clue:'Queen of England and Scotland and Ireland' },
        { number:38, row:6, col:10, len:5, clue:'French composer and exponent of Impressionism' },
        { number:39, row:7, col:0, len:3, clue:'3-letter word' },
        { number:40, row:7, col:4, len:7, clue:'Any piece of work that is undertaken or attempted' },
        { number:42, row:7, col:12, len:3, clue:'3-letter word' },
        { number:43, row:8, col:0, len:5, clue:'Any property detected by the olfactory system' },
        { number:45, row:8, col:6, len:4, clue:'Pinkish table wine from red grapes whose skins were removed after f...' },
        { number:46, row:8, col:11, len:4, clue:'In addition' },
        { number:47, row:9, col:0, len:5, clue:'The adult male singing voice above baritone' },
        { number:48, row:9, col:6, len:6, clue:'Either of two folds of skin that can be moved to cover or open the eye' },
        { number:50, row:10, col:2, len:4, clue:'Exchange or deliver for money or its equivalent' },
        { number:52, row:10, col:9, len:6, clue:'The act of going from one place to another' },
        { number:56, row:11, col:0, len:6, clue:'The principal dish of a meal' },
        { number:58, row:11, col:7, len:4, clue:'A knife used as a weapon' },
        { number:60, row:11, col:12, len:3, clue:'3-letter word' },
        { number:61, row:12, col:0, len:4, clue:'An area within a building enclosed by walls and floor and ceiling' },
        { number:62, row:12, col:5, len:10, clue:'Any of various antibiotics obtained from Penicillium molds  and use...' },
        { number:65, row:13, col:0, len:4, clue:'An island to the northwest of Wales' },
        { number:66, row:13, col:5, len:4, clue:'An implement used in the practice of a vocation' },
        { number:67, row:13, col:10, len:5, clue:'A thermoplastic polyamide' },
        { number:68, row:14, col:0, len:4, clue:'4-letter word' },
        { number:69, row:14, col:5, len:4, clue:'A long loud emotional utterance' },
        { number:70, row:14, col:10, len:5, clue:'A frame of iron bars to hold a fire' }
      ],
      down: [

        { number:1, row:0, col:0, len:5, clue:'Building material used as siding or roofing' },
        { number:2, row:0, col:1, len:5, clue:'The whole amount' },
        { number:3, row:0, col:2, len:5, clue:'5-letter word' },
        { number:4, row:0, col:3, len:3, clue:'3-letter word' },
        { number:5, row:0, col:4, len:6, clue:'Spanish general whose armies took control of Spain in 1939 and who ...' },
        { number:6, row:0, col:6, len:4, clue:'A person who is opposed' },
        { number:7, row:0, col:7, len:4, clue:'A structure consisting of something wound in a continuous series of...' },
        { number:8, row:0, col:8, len:3, clue:'Increase the number of rotations per minute' },
        { number:9, row:0, col:9, len:5, clue:'An exclusive group of people' },
        { number:10, row:0, col:11, len:7, clue:'Textual matter that is added onto a publication' },
        { number:11, row:0, col:12, len:9, clue:'A reckless impetuous irresponsible person' },
        { number:12, row:0, col:13, len:4, clue:'A Hebrew shepherd and minor prophet' },
        { number:13, row:0, col:14, len:4, clue:'Someone who wastes time' },
        { number:18, row:2, col:5, len:6, clue:'Conqueror of Gaul and master of Italy' },
        { number:23, row:3, col:10, len:5, clue:'The locus of feelings and intuitions' },
        { number:25, row:4, col:3, len:3, clue:'The branch of engineering that deals with the use of computers and ...' },
        { number:28, row:5, col:6, len:5, clue:'The rattling noise produced when snoring' },
        { number:29, row:5, col:7, len:5, clue:'Derive or receive pleasure from' },
        { number:30, row:5, col:8, len:5, clue:'5-letter word' },
        { number:32, row:5, col:13, len:4, clue:'A quantifier meaning not as great in amount or degree' },
        { number:33, row:5, col:14, len:4, clue:'The lowest female singing voice' },
        { number:34, row:6, col:0, len:4, clue:'4-letter word' },
        { number:35, row:6, col:1, len:4, clue:'The present location' },
        { number:36, row:6, col:2, len:9, clue:'9-letter word' },
        { number:40, row:7, col:4, len:5, clue:'5-letter word' },
        { number:41, row:7, col:9, len:6, clue:'A branch of the Indo-European languages that  was spread widely ove...' },
        { number:44, row:8, col:3, len:7, clue:'7-letter word' },
        { number:46, row:8, col:11, len:3, clue:'An enzyme found in mammals that can catalyze the deamination of ade...' },
        { number:49, row:9, col:10, len:6, clue:'United States writer remembered for his stories' },
        { number:51, row:10, col:5, len:5, clue:'The extent downward or backward or inward' },
        { number:53, row:10, col:12, len:5, clue:'Mexican revolutionary leader' },
        { number:54, row:10, col:13, len:5, clue:'British poet  who won the Nobel prize for literature' },
        { number:55, row:10, col:14, len:5, clue:'5-letter word' },
        { number:56, row:11, col:0, len:4, clue:'4-letter word' },
        { number:57, row:11, col:1, len:4, clue:'The middle of the day' },
        { number:58, row:11, col:7, len:4, clue:'Precipitation falling from clouds in the form of ice crystals' },
        { number:59, row:11, col:8, len:4, clue:'A local and well-defined elevation of the land' },
        { number:63, row:12, col:6, len:3, clue:'3-letter word' },
        { number:64, row:12, col:11, len:3, clue:'3-letter word' }
      ],
    },
  },


  {
    solution: [
      ['S','A','L','T','I',null,'S','C','A','N',null,'A','V','E','S'],
      ['K','N','O','W','N',null,'O','H','I','O',null,'E','L','L','A'],
      ['I','N','T','O','L','E','R','A','N','T',null,'R','A','S','I'],
      ['L','O','U',null,'A','N','T','I',null,'E','R','O','D','E','D'],
      ['L','Y','S','I','N','E',null,null,null,'D','E','S','I',null,null],
      [null,null,null,'A','D','R','I','A','N',null,'N','O','S','E','D'],
      ['S','F','W','N',null,'G','O','L','I',null,'A','L','L','A','Y'],
      ['L','I','H',null,'C','Y','N','I','C','A','L',null,'A','S','E'],
      ['A','F','O','U','L',null,'I','N','K','S',null,'O','V','E','R'],
      ['V','O','L','T','A',null,'C','E','Y','L','O','N',null,null,null],
      [null,null,'E','R','I','C',null,null,null,'E','M','E','R','G','E'],
      ['C','I','N','E','M','A',null,'F','L','E','E',null,'O','E','A'],
      ['A','L','E','C',null,'B','A','L','L','P','L','A','Y','E','R'],
      ['D','I','S','H',null,'A','H','O','Y',null,'E','R','A','S','E'],
      ['E','A','S','T',null,'L','A','W','N',null,'T','I','L','E','D'],
    ],
    clues: {
      across: [

        { number:1, row:0, col:0, len:5, clue:'5-letter word' },
        { number:6, row:0, col:6, len:4, clue:'Examine minutely or intensely' },
        { number:10, row:0, col:11, len:4, clue:'The class of birds' },
        { number:14, row:1, col:0, len:5, clue:'Be cognizant or aware of a fact or a specific piece of information' },
        { number:15, row:1, col:6, len:4, clue:'A midwestern state in north central United States in the Great Lake...' },
        { number:16, row:1, col:11, len:4, clue:'4-letter word' },
        { number:17, row:2, col:0, len:10, clue:'Unwilling to tolerate difference of opinion' },
        { number:19, row:2, col:11, len:4, clue:'4-letter word' },
        { number:20, row:3, col:0, len:3, clue:'3-letter word' },
        { number:21, row:3, col:4, len:4, clue:'A person who is opposed' },
        { number:22, row:3, col:9, len:6, clue:'Become ground down or deteriorate' },
        { number:24, row:4, col:0, len:6, clue:'An essential amino acid found in proteins' },
        { number:26, row:4, col:9, len:4, clue:'4-letter word' },
        { number:27, row:5, col:3, len:6, clue:'Roman Emperor who was the adoptive son of Trajan' },
        { number:31, row:5, col:10, len:5, clue:'Search or inquire in a meddlesome way' },
        { number:34, row:6, col:0, len:4, clue:'4-letter word' },
        { number:37, row:6, col:5, len:4, clue:'4-letter word' },
        { number:38, row:6, col:10, len:5, clue:'Lessen the intensity of or calm' },
        { number:39, row:7, col:0, len:3, clue:'3-letter word' },
        { number:40, row:7, col:4, len:7, clue:'7-letter word' },
        { number:42, row:7, col:12, len:3, clue:'3-letter word' },
        { number:43, row:8, col:0, len:5, clue:'5-letter word' },
        { number:45, row:8, col:6, len:4, clue:'A liquid used for printing or writing or drawing' },
        { number:46, row:8, col:11, len:4, clue:'The division of play during which six balls are bowled at the batsm...' },
        { number:47, row:9, col:0, len:5, clue:'Italian physicist after whom the volt is named' },
        { number:48, row:9, col:6, len:6, clue:'An island in the Indian Ocean off the southeastern coast of India' },
        { number:50, row:10, col:2, len:4, clue:'4-letter word' },
        { number:52, row:10, col:9, len:6, clue:'Come out into view, as from concealment' },
        { number:56, row:11, col:0, len:6, clue:'A medium that disseminates moving pictures' },
        { number:58, row:11, col:7, len:4, clue:'Run away quickly' },
        { number:60, row:11, col:12, len:3, clue:'3-letter word' },
        { number:61, row:12, col:0, len:4, clue:'4-letter word' },
        { number:62, row:12, col:5, len:10, clue:'An athlete who plays baseball' },
        { number:65, row:13, col:0, len:4, clue:'A particular item of prepared food' },
        { number:66, row:13, col:5, len:4, clue:'4-letter word' },
        { number:67, row:13, col:10, len:5, clue:'Remove from memory or existence' },
        { number:68, row:14, col:0, len:4, clue:'The cardinal compass point that is at 90 degrees' },
        { number:69, row:14, col:5, len:4, clue:'A field of cultivated and mowed grass' },
        { number:70, row:14, col:10, len:5, clue:'Cover with tiles' }
      ],
      down: [

        { number:1, row:0, col:0, len:5, clue:'An ability that has been acquired by training' },
        { number:2, row:0, col:1, len:5, clue:'5-letter word' },
        { number:3, row:0, col:2, len:5, clue:'Native to eastern Asia' },
        { number:4, row:0, col:3, len:3, clue:'The cardinal number that is the sum of one and one or a numeral rep...' },
        { number:5, row:0, col:4, len:6, clue:"Situated away from an area's coast or border" },
        { number:6, row:0, col:6, len:4, clue:'A category of things distinguished by some common characteristic or...' },
        { number:7, row:0, col:7, len:4, clue:'4-letter word' },
        { number:8, row:0, col:8, len:3, clue:'3-letter word' },
        { number:9, row:0, col:9, len:5, clue:'Make mention of' },
        { number:10, row:0, col:11, len:7, clue:'A cloud of solid or liquid particles in a gas' },
        { number:11, row:0, col:12, len:9, clue:'9-letter word' },
        { number:12, row:0, col:13, len:4, clue:'4-letter word' },
        { number:13, row:0, col:14, len:4, clue:'Express in words' },
        { number:18, row:2, col:5, len:6, clue:'A thermodynamic quantity equivalent to the capacity of a physical s...' },
        { number:23, row:3, col:10, len:5, clue:'Of or relating to the kidneys' },
        { number:25, row:4, col:3, len:3, clue:'3-letter word' },
        { number:28, row:5, col:6, len:5, clue:'The dialect of Ancient Greek spoken and written in Attica and Athen...' },
        { number:29, row:5, col:7, len:5, clue:'Place in a line or arrange so as to be parallel or straight' },
        { number:30, row:5, col:8, len:5, clue:'5-letter word' },
        { number:32, row:5, col:13, len:4, clue:'Freedom from difficulty or hardship or effort' },
        { number:33, row:5, col:14, len:4, clue:'Someone whose job is to dye cloth' },
        { number:34, row:6, col:0, len:4, clue:'4-letter word' },
        { number:35, row:6, col:1, len:4, clue:'Inventory accounting in which the oldest items  are assumed to be t...' },
        { number:36, row:6, col:2, len:9, clue:'An undivided or unbroken completeness or totality with nothing wanting' },
        { number:40, row:7, col:4, len:5, clue:'An assertion of a right' },
        { number:41, row:7, col:9, len:6, clue:'In a state of sleep' },
        { number:44, row:8, col:3, len:7, clue:'A city in the central Netherlands' },
        { number:46, row:8, col:11, len:3, clue:'The smallest whole number or a numeral representing this number' },
        { number:49, row:9, col:10, len:6, clue:'Beaten eggs or an egg mixture cooked until just set' },
        { number:51, row:10, col:5, len:5, clue:'A clique  that seeks power usually through intrigue' },
        { number:53, row:10, col:12, len:5, clue:'Stag with antlers of 12 or more branches' },
        { number:54, row:10, col:13, len:5, clue:'Web-footed long-necked typically gregarious migratory aquatic birds...' },
        { number:55, row:10, col:14, len:5, clue:'Having ears  or having ears of a specified kind' },
        { number:56, row:11, col:0, len:4, clue:'4-letter word' },
        { number:57, row:11, col:1, len:4, clue:'An ancient city in Asia Minor that was the site of the Trojan War' },
        { number:58, row:11, col:7, len:4, clue:'The motion characteristic of fluids' },
        { number:59, row:11, col:8, len:4, clue:'4-letter word' },
        { number:63, row:12, col:6, len:3, clue:'3-letter word' },
        { number:64, row:12, col:11, len:3, clue:'3-letter word' }
      ],
    },
  },


];

const EPOCH = new Date('2026-05-01');

function getPuzzleForDay(dayOffset) {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const days = Math.floor((today - EPOCH) / 86400000) + (dayOffset || 0);
  if (PUZZLES.length === 0) return { empty: true, dayIndex: days };
  const idx = ((days % PUZZLES.length) + PUZZLES.length) % PUZZLES.length;
  return { ...PUZZLES[idx], dayIndex: days };
}
